### ISSUE TITLE
Wrong response status code

### ISSUE THREAD

**Issue by mageshr2016** [Gnzlt/AlexaApiAiBridge#1]
Hi - Am trying to use your example set and completed all the configurations. But when I type in text as 'hello' from Alexa test simulator, I get an error as "ssml": "<speak> Wrong response status code. </speak>" When I debugged, by adding loggers and the problem was due to session id. The session id from aws is 40+ characters long but it gives error from API.AI that it has to be 36 chars long, max. Any idea how to overcome this? Looks like we are using alexa session id throughout.

**Comment by mageshr2016** [comment]
Since session id was of format 'SessionId.random 36 char string'. I did a replace of 'SessionId.' with empty string to reduce it to 36 chars and it works fine for me. Pls let me know if there is any other better way to do it. I see that your code has this logic - sessionId.split('amzn1.echo-api.session.').pop(), and am not sure if anything changed with the way session id is generated in alexa now. I have a work around for now. Thanks.

**Comment by swbradshaw** [comment]
Fix is in the bottom function:
```
function setAlexaSessionId(sessionId) {
    alexaSessionId = sessionId.split('SessionId.').pop();
}
```

**Comment by Gnzlt** [comment]
Exactly, as @swbradshaw points out, I'm using a shorter version of the Api.ai `sessionId`.

**Comment by mageshr2016** [comment]
Thanks. I already did that and I wanted to make sure that is indeed the right fix or if am missing anything. Thanks for the inputs.

**Comment by swbradshaw** [comment]
@iosnewbie2016  @Gnzlt  The real issue here is Session Id is different when you use Alexa simulator vs actual device.  In testing, the session starts with "SessionId". When you use a real device, it starts with "amzn1.echo-api.session".  With the current code, you cannot test from simulator because the session id is too long. I provided a workaround earlier, but that won't work when you goto production. I believe function setAlexaSessionId  should really handle both.  Something like this:


```
function setAlexaSessionId(sessionId) {
    if (sessionId.indexOf('amzn1.echo-api.session') > -1) {
      alexaSessionId = sessionId.split('amzn1.echo-api.session.').pop();   
    }
    else {
      alexaSessionId = sessionId.split('SessionId.').pop();
    }
}
```

**Comment by mageshr2016** [comment]
@swbradshaw - Thanks for your insights. I was not aware that we have different mechanisms in simulator vs real device. Thanks again.
