### ISSUE TITLE
Update setAlexaSessionId

### ISSUE THREAD

**Issue by juliusspencer** [Gnzlt/AlexaApiAiBridge#2]
[On line](https://github.com/Gnzlt/AlexaApiAiBridge/blob/master/index.js#L104) can you change it to:

> alexaSessionId = sessionId.split('SessionId.').pop();

I don't know how to issue a merge request without the ability to add a branch to your repository and push it up.

Without this the sessionId is too long.

**Comment by juliusspencer** [comment]
I ended up using the following which works with the hardware as well as the Service Simulator:

> if (sessionId.includes('SessionId.'))
>         alexaSessionId = sessionId.split('SessionId.').pop();
>     if (sessionId.includes('amzn1.echo-api.session.'))
>         alexaSessionId = sessionId.split('amzn1.echo-api.session.').pop();

**Comment by Gnzlt** [comment]
Hi @juliusspencer, sorry I had no time to check the issue.
Thanks for the suggestion! I'll try your solution and include it in the next release 👍
