### ISSUE TITLE
Wrong response status code

### ISSUE THREAD

**Issue by jrob00** [Gnzlt/AlexaApiAiBridge#3]
Hey there, thanks for putting this together. Just a note to mention that I followed your README and I only get the following response back from the Lambda:
```
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "SSML",
      "ssml": "<speak> Wrong response status code. </speak>"
    },
    "speechletResponse": {
      "outputSpeech": {
        "ssml": "<speak> Wrong response status code. </speak>"
      },
      "shouldEndSession": true
    }
  },
  "sessionAttributes": {}
}
```

**Comment by patcat** [comment]
@jrob00 I had the same issue. I've got a fix for this over at https://github.com/Gnzlt/AlexaApiAiBridge/pull/4 :)

Hope that helps!

**Comment by jrob00** [comment]
@patcat amazing. excellent work and thank you!!
