### ISSUE TITLE
Getting an error when testing Alexa

### ISSUE THREAD

**Issue by bryanchoi** [Gnzlt/AlexaApiAiBridge#6]
After following your steps, i get this error when testing my utterance: The remote endpoint could not be called, or the response it returned was invalid. Please advise.

**Comment by nareddyt** [comment]
Does this appear in the amazon developer console while testing your utterance? Do you have a log trace with that error? Without any logs, I'm guessing that Alexa Skills could not make a connection to your lambda function. 

I followed the steps and everything worked fine for me. Make sure you set up all your intents correctly in the configuration and that the lambda function is in one of the two supported regions.
