### ISSUE TITLE
How to send anything and everything said to Alexa in its true form to bridge

### ISSUE THREAD

**Issue by jTariq** [Gnzlt/AlexaApiAiBridge#8]
How to send anything and everything said to Alexa in its true form to bridge.
I am trying to invoke intents with utterances containing mixture of date, time number and words.

How to configure such intent and what to specify in sample utterances

**Comment by Gnzlt** [comment]
I don't understand what you mean. The library is already sending all that information to Dialogflow(aka Api.ai) and it's their responsibility to handle it properly.
You should check your `Intents` within your project in Dialogflow.
